/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analizador_lexico.front;

import analizador_lexico.utils.Archive;
import java.awt.BorderLayout;
import java.awt.Font;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;

/**
 *
 * @author tuxrex
 */
public class Analizer extends javax.swing.JFrame {

    /**
     * Creates new form Analizer
     */
    JLabel position;
    JLabel lineNumberLabel;
    Font font = new Font("Liberation Sans", Font.BOLD, 18);
    private int lineNumber;
    private int columnNumber;
    private Archive archivo;
    private String texto;
    private JFileChooser file;
    public Analizer() {
        initComponents();
        //modifyTextArea();
        lineNumberLabel.setFont(font);
        archivo=new Archive();
        archivo.setPath(path_file);
        file=new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tobbe1 = new javax.swing.JTabbedPane();
        error_o_token = new javax.swing.JPanel();
        btn_save_Archivo = new javax.swing.JButton();
        run = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_error_tokens = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_code = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_Archivo1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        path_file = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        go_analizer = new javax.swing.JMenu();
        go_graphics = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tobbe1.setEnabled(false);

        btn_save_Archivo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn_save_Archivo.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/save.png")); // NOI18N
        btn_save_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_ArchivoActionPerformed(evt);
            }
        });

        run.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        run.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/play.png")); // NOI18N

        table_error_tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_error_tokens);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        area_code.setColumns(20);
        area_code.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        area_code.setRows(5);
        jScrollPane1.setViewportView(area_code);
        //Aqui va la mitad de la creacion de a fila y columna
        area_code.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateLineNumbersLater(); // Use invokeLater
                updateCursorPositionLater();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateLineNumbersLater(); // Use invokeLater
                updateCursorPositionLater();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateLineNumbersLater(); // Use invokeLater
                updateCursorPositionLater();
            }
        });
        position=new JLabel("Linea: "+1+" Columna: "+1);
        position.setVerticalAlignment(JLabel.BOTTOM);
        lineNumberLabel = new JLabel(" 1 ");
        lineNumberLabel.setVerticalAlignment(JLabel.TOP);
        area_code.add(position);
        area_code.add(lineNumberLabel);

        //JScrollPane scrollPane = new JScrollPane(area_code);
        jScrollPane1.setRowHeaderView(lineNumberLabel);
        jScrollPane1.setColumnHeaderView(position);

        getContentPane().add(jScrollPane1, BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        btn_Archivo1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btn_Archivo1.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/add_archive.png")); // NOI18N
        btn_Archivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Archivo1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel3.setText("Analizador Lexico");

        path_file.setEditable(false);
        path_file.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout error_o_tokenLayout = new javax.swing.GroupLayout(error_o_token);
        error_o_token.setLayout(error_o_tokenLayout);
        error_o_tokenLayout.setHorizontalGroup(
            error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(error_o_tokenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(error_o_tokenLayout.createSequentialGroup()
                        .addComponent(path_file, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Archivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btn_save_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, error_o_tokenLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257)))
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, error_o_tokenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(546, 546, 546))
        );
        error_o_tokenLayout.setVerticalGroup(
            error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(error_o_tokenLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(error_o_tokenLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(error_o_tokenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Archivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(error_o_tokenLayout.createSequentialGroup()
                                .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(error_o_tokenLayout.createSequentialGroup()
                                        .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(error_o_tokenLayout.createSequentialGroup()
                                                .addComponent(btn_save_Archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)))
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, error_o_tokenLayout.createSequentialGroup()
                                        .addComponent(path_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)))
                                .addGroup(error_o_tokenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(run, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        tobbe1.addTab("", error_o_token);

        jLabel1.setText("Aqui va las graficas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel1)
                .addContainerGap(906, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(679, Short.MAX_VALUE))
        );

        tobbe1.addTab("", jPanel3);

        jLabel4.setText("Aqui va acerca de mi ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(646, 646, 646)
                .addComponent(jLabel4)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4)
                .addContainerGap(601, Short.MAX_VALUE))
        );

        tobbe1.addTab("", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tobbe1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tobbe1)
        );

        go_analizer.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/icons8-archive-list-of-parts-40.png")); // NOI18N
        go_analizer.setText("Archivo");
        go_analizer.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        go_analizer.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                go_analizerMenuSelected(evt);
            }
        });
        go_analizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_analizerActionPerformed(evt);
            }
        });
        jMenuBar1.add(go_analizer);

        go_graphics.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/icons8-vector-64.png")); // NOI18N
        go_graphics.setText("Generar Grafico");
        go_graphics.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        go_graphics.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                go_graphicsMenuSelected(evt);
            }
        });
        jMenuBar1.add(go_graphics);

        jMenu3.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/help.png")); // NOI18N
        jMenu3.setText("Ayuda");
        jMenu3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("/home/tuxrex/NetBeansProjects/analizador_lexico/src/main/java/analizador_lexico/img/about.png")); // NOI18N
        jMenu4.setText("Acerca de");
        jMenu4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Archivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Archivo1ActionPerformed
       this.file = new JFileChooser();
        //FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT",".txt");
        //file.setFileFilter(filtro);
        int selection =file.showOpenDialog(this);
        if(selection==JFileChooser.APPROVE_OPTION){
            archivo.chooseFile(file);
            texto=archivo.getTexto();
            area_code.setText(texto);
        }
        
        System.out.println(texto);
        
    }//GEN-LAST:event_btn_Archivo1ActionPerformed

    private void btn_save_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_ArchivoActionPerformed
        this.file = new JFileChooser();
        //FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.TXT",".txt");
        //file.setFileFilter(filtro);
        int selection =file.showSaveDialog(this);
        if(selection==JFileChooser.APPROVE_OPTION){
            archivo.setArea(area_code);
            archivo.saveFile(file);
        }
        
    }//GEN-LAST:event_btn_save_ArchivoActionPerformed

    private void go_analizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_analizerActionPerformed
      //  tobbe1.setSelectedIndex(1);
    }//GEN-LAST:event_go_analizerActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
       tobbe1.setSelectedIndex(0);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
         tobbe1.setSelectedIndex(2);
    }//GEN-LAST:event_jMenu4MenuSelected

    private void go_analizerMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_go_analizerMenuSelected
         tobbe1.setSelectedIndex(0);
    }//GEN-LAST:event_go_analizerMenuSelected

    private void go_graphicsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_go_graphicsMenuSelected
         tobbe1.setSelectedIndex(1);
    }//GEN-LAST:event_go_graphicsMenuSelected


private void updateLineNumbersLater() {
        SwingUtilities.invokeLater(this::updateLineNumbers);
    }
    private void updateCursorPositionLater() {
        SwingUtilities.invokeLater(this::updateCursorPosition);
    }

    private void updateLineNumbers() {
        try {
            int caretPosition = area_code.getCaretPosition();
            lineNumber = area_code.getLineOfOffset(caretPosition) + 1;
            lineNumberLabel.setText(getLineNumberText(lineNumber));

        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }
     private void updateCursorPosition() {
        try {
            int caretPosition = area_code.getCaretPosition();
            lineNumber = area_code.getLineOfOffset(caretPosition) + 1;
            columnNumber = caretPosition - area_code.getLineStartOffset(lineNumber - 1) + 1;
            position.setText("Linea: " + lineNumber + ", Columna: " + columnNumber);

        } catch (BadLocationException e) {
            e.printStackTrace();
        }
    }
    private String getLineNumberText(int totalLines) {
        StringBuilder numbersText = new StringBuilder();
        for (int i = 1; i <= totalLines; i++) {
            numbersText.append(i).append("<br>");
        }
        return "<html>" + numbersText.toString() + "</html>";
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_code;
    private javax.swing.JButton btn_Archivo1;
    private javax.swing.JButton btn_save_Archivo;
    private javax.swing.JPanel error_o_token;
    private javax.swing.JMenu go_analizer;
    private javax.swing.JMenu go_graphics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField path_file;
    private javax.swing.JButton run;
    private javax.swing.JTable table_error_tokens;
    private javax.swing.JTabbedPane tobbe1;
    // End of variables declaration//GEN-END:variables
}
